/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.pedido;

import control.BebidaControl;
import control.PastelControl;
import control.PedidoControl;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.bean.BebidaBEAN;
import model.bean.PastelBEAN;
import model.bean.PedidoBEAN;

/**
 *
 * @author claud
 */
public class FrmConsultarPedido extends javax.swing.JFrame {

    public void visuDataHora() {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Calendar date = Calendar.getInstance();
        int hora = date.get(Calendar.HOUR_OF_DAY) - 1;
        int min = date.get(Calendar.MINUTE);
        lblDataHora.setText(hora + ":" + min + " - " + formatter.format(date.getTime()));
    }

    public void visuGeral() {
        PastelBEAN pastelBEAN = new PastelBEAN();
        PastelControl contPast = new PastelControl();
        BebidaBEAN bebidaBEAN = new BebidaBEAN();
        BebidaControl contBeb = new BebidaControl();

        PedidoControl cont = new PedidoControl();
        List<PedidoBEAN> listaDeDados = new ArrayList<>();
        listaDeDados = cont.listar();

        DefaultTableModel tbm = (DefaultTableModel) tblDados.getModel();
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        int i = 0;
        for (PedidoBEAN pedBEAN : listaDeDados) {
            tbm.addRow(new String[1]);
            tblDados.setValueAt(pedBEAN.getIdPedido(), i, 0);

            pastelBEAN.setIdPastel(pedBEAN.getIdPastel());
            pastelBEAN = contPast.consultarID(pastelBEAN);
            tblDados.setValueAt(pastelBEAN.getNome_pastel(), i, 1);

            tblDados.setValueAt(pedBEAN.getQtdePastel(), i, 2);

            bebidaBEAN.setIdBebida(pedBEAN.getIdBebida());
            bebidaBEAN = contBeb.consultarID(bebidaBEAN);
            tblDados.setValueAt(bebidaBEAN.getNome_bebida(), i, 3);

            tblDados.setValueAt(pedBEAN.getQtdeBebida(), i, 4);
            i++;
        }
    }

    public void visuResult(PedidoBEAN pedBEAN) {
        PastelBEAN pastelBEAN = new PastelBEAN();
        PastelControl contPast = new PastelControl();
        BebidaBEAN bebidaBEAN = new BebidaBEAN();
        BebidaControl contBeb = new BebidaControl();

        DefaultTableModel tbm = (DefaultTableModel) tblDados.getModel();
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        tbm.addRow(new String[1]);
        tblDados.setValueAt(pedBEAN.getIdPedido(), 0, 0);

        pastelBEAN.setIdPastel(pedBEAN.getIdPastel());
        pastelBEAN = contPast.consultarID(pastelBEAN);
        tblDados.setValueAt(pastelBEAN.getNome_pastel(), 0, 1);

        tblDados.setValueAt(pedBEAN.getQtdePastel(), 0, 2);

        bebidaBEAN.setIdBebida(pedBEAN.getIdBebida());
        bebidaBEAN = contBeb.consultarID(bebidaBEAN);
        tblDados.setValueAt(bebidaBEAN.getNome_bebida(), 0, 3);

        tblDados.setValueAt(pedBEAN.getQtdeBebida(), 0, 4);
    }

    public FrmConsultarPedido() {
        initComponents();
        visuGeral();
        visuDataHora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsultar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jScrollPane26 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();
        chkID = new javax.swing.JCheckBox();
        lblDataHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Consultar pedidos");

        txtID.setEnabled(false);
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Pastel", "Qtde Pastéis", "Bebida", "Qtde Bebidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDados.setAlignmentX(6.0F);
        tblDados.setAlignmentY(1.0F);
        tblDados.setRowHeight(25);
        jScrollPane26.setViewportView(tblDados);

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Status:");

        chkID.setText("ID do registro");
        chkID.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkIDStateChanged(evt);
            }
        });
        chkID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIDActionPerformed(evt);
            }
        });

        lblDataHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDataHora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDataHora.setText("Hora - Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDataHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkID)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultar))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane26)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(lblDataHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar)
                    .addComponent(chkID))
                .addGap(51, 51, 51)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        PedidoBEAN pedBEAN = new PedidoBEAN();
        PedidoControl contPed = new PedidoControl();

        if (chkID.isSelected() == true) {
            try {
                pedBEAN.setIdPedido(Integer.parseInt(txtID.getText()));
                pedBEAN = contPed.consultarID(pedBEAN);
                visuResult(pedBEAN);
                lblStatus.setText(pedBEAN.getStatus());
            } catch (NumberFormatException e) {
                lblStatus.setText("Sem ou ID para fazer a consulta.");
                visuGeral();
            } catch (NullPointerException e) {
                lblStatus.setText("Sem ID para fazer a consulta.");
                visuGeral();
            }

        } else {
            lblStatus.setText("Sem ou ID para fazer a consulta.");
            visuGeral();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        FrmPedido menuProdutos = new FrmPedido();
        this.dispose();
        menuProdutos.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        String caracteres = "0987654321.";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIDKeyTyped

    private void chkIDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkIDStateChanged
        if (chkID.isSelected() == true) {
            txtID.enable(true);
        } else {
            txtID.enable(false);
            txtID.setText(null);
        }
    }//GEN-LAST:event_chkIDStateChanged

    private void chkIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIDActionPerformed
        if (chkID.isSelected() == true) {
            txtID.enable(true);
        } else {
            txtID.enable(false);
            txtID.setText(null);
        }
    }//GEN-LAST:event_chkIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConsultarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox chkID;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JLabel lblDataHora;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblDados;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
