/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.pedido;

import control.BebidaControl;
import control.PastelControl;
import control.PedidoControl;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import model.bean.BebidaBEAN;
import model.bean.PastelBEAN;
import model.bean.PedidoBEAN;

/**
 *
 * @author claud
 */
public class FrmInserirPedido extends javax.swing.JFrame {

    public void visuDataHora() {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Calendar date = Calendar.getInstance();
        int hora = date.get(Calendar.HOUR_OF_DAY) - 1;
        int min = date.get(Calendar.MINUTE);
        lblDataHora.setText(hora + ":" + min + " - " + formatter.format(date.getTime()));
    }

    public void visuGeral() {
        PastelBEAN pastelBEAN = new PastelBEAN();
        PastelControl contPast = new PastelControl();
        BebidaBEAN bebidaBEAN = new BebidaBEAN();
        BebidaControl contBeb = new BebidaControl();

        PedidoControl cont = new PedidoControl();
        List<PedidoBEAN> listaDeDados = new ArrayList<>();
        listaDeDados = cont.listar();

        DefaultTableModel tbm = (DefaultTableModel) tblDados.getModel();
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        int i = 0;
        for (PedidoBEAN pedBEAN : listaDeDados) {
            tbm.addRow(new String[1]);
            tblDados.setValueAt(pedBEAN.getIdPedido(), i, 0);

            pastelBEAN.setIdPastel(pedBEAN.getIdPastel());
            pastelBEAN = contPast.consultarID(pastelBEAN);
            tblDados.setValueAt(pastelBEAN.getNome_pastel(), i, 1);

            tblDados.setValueAt(pedBEAN.getQtdePastel(), i, 2);

            bebidaBEAN.setIdBebida(pedBEAN.getIdBebida());
            bebidaBEAN = contBeb.consultarID(bebidaBEAN);
            tblDados.setValueAt(bebidaBEAN.getNome_bebida(), i, 3);

            tblDados.setValueAt(pedBEAN.getQtdeBebida(), i, 4);
            i++;
        }
    }

    public void visuPastel() {
        DefaultListModel model = new DefaultListModel();
        List<PastelBEAN> listaDeDados = new ArrayList<>();
        PastelControl contPast = new PastelControl();
        listaDeDados = contPast.listar();
        int i = 0;
        for (PastelBEAN pastelBEAN : listaDeDados) {
            model.addElement(new String[1]);
            model.setElementAt(pastelBEAN.getNome_pastel(), i);
            i++;
        }
        listaPastel.setModel(model);
    }

    public void visuBebida() {
        DefaultListModel model = new DefaultListModel();
        List<BebidaBEAN> listaDeDados = new ArrayList<>();
        BebidaControl contBeb = new BebidaControl();
        listaDeDados = contBeb.listar();
        int i = 0;
        for (BebidaBEAN bebidaBEAN : listaDeDados) {
            model.addElement(new String[1]);
            model.setElementAt(bebidaBEAN.getNome_bebida(), i);
            i++;
        }
        listaBebida.setModel(model);
    }

    public FrmInserirPedido() {
        initComponents();
        visuGeral();
        visuPastel();
        visuBebida();
        visuDataHora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane26 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();
        chkPastel = new javax.swing.JCheckBox();
        chkBebida = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQtdeBebida = new javax.swing.JTextField();
        txtQtdePastel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPastel = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaBebida = new javax.swing.JList<>();
        lblDataHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Novo PEDIDO");

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Pastel", "Qtde Pastéis", "Bebida", "Qtde Bebidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDados.setAlignmentX(6.0F);
        tblDados.setAlignmentY(1.0F);
        tblDados.setRowHeight(25);
        jScrollPane26.setViewportView(tblDados);

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Status:");

        chkPastel.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        chkPastel.setText("Pastel");
        chkPastel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkPastelStateChanged(evt);
            }
        });
        chkPastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPastelActionPerformed(evt);
            }
        });
        chkPastel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                chkPastelPropertyChange(evt);
            }
        });

        chkBebida.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        chkBebida.setText("Bebida");
        chkBebida.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkBebidaStateChanged(evt);
            }
        });
        chkBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBebidaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jLabel3.setText("Quantidade:");

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 11)); // NOI18N
        jLabel4.setText("Quantidade:");

        txtQtdeBebida.setEnabled(false);
        txtQtdeBebida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtdeBebidaKeyTyped(evt);
            }
        });

        txtQtdePastel.setEnabled(false);
        txtQtdePastel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtdePastelKeyTyped(evt);
            }
        });

        listaPastel.setEnabled(false);
        jScrollPane1.setViewportView(listaPastel);

        listaBebida.setEnabled(false);
        jScrollPane3.setViewportView(listaBebida);

        lblDataHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDataHora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDataHora.setText("Hora - Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkPastel)
                                        .addGap(14, 14, 14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(txtQtdePastel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(chkBebida)
                                        .addGap(4, 4, 4))
                                    .addComponent(txtQtdeBebida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane26, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(lblDataHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkPastel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdePastel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkBebida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdeBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        PedidoBEAN pedBEAN = new PedidoBEAN();
        PedidoControl contPed = new PedidoControl();
        PastelBEAN pastelBEAN = new PastelBEAN();
        PastelControl contPast = new PastelControl();
        BebidaBEAN bebidaBEAN = new BebidaBEAN();
        BebidaControl contBeb = new BebidaControl();

        List<PastelBEAN> listaDePastel = new ArrayList<>();
        List<BebidaBEAN> listaDeBebida = new ArrayList<>();

        if (chkBebida.isSelected() == false && chkPastel.isSelected() == false) {
            lblStatus.setText("Sem pastéis ou bebidas no pedido");
        } else {
            if (chkPastel.isSelected() == true) {
                pastelBEAN.setNome_pastel(listaPastel.getSelectedValue());
                listaDePastel = contPast.consultarNome(pastelBEAN);
                pastelBEAN = listaDePastel.get(0);
                pedBEAN.setIdPastel(pastelBEAN.getIdPastel());
                pedBEAN.setQtdePastel(Integer.parseInt(txtQtdePastel.getText()));
            }
            if (chkBebida.isSelected() == true) {
                bebidaBEAN.setNome_bebida(listaBebida.getSelectedValue());
                listaDeBebida = contBeb.consultarNome(bebidaBEAN);
                bebidaBEAN = listaDeBebida.get(0);
                pedBEAN.setIdBebida(bebidaBEAN.getIdBebida());
                pedBEAN.setQtdeBebida(Integer.parseInt(txtQtdeBebida.getText()));
            }
            pedBEAN = contPed.inserir(pedBEAN);
            lblStatus.setText(pedBEAN.getStatus());
            /*
            if (pedBEAN.getIdPastel() > 0 && pedBEAN.getIdBebida() > 0) {
                pedBEAN = contPed.inserir(pedBEAN);
                lblStatus.setText(pedBEAN.getStatus());
            } else {
                lblStatus.setText("Ocorreu um erro\n" + pedBEAN.getIdPastel() + " bebida " + pedBEAN.getIdBebida());
                JOptionPane.showMessageDialog(null, pastelBEAN.getNome_pastel());
                JOptionPane.showMessageDialog(null, bebidaBEAN.getNome_bebida());
            }
             */
        }
        visuGeral();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        FrmPedido pedidos = new FrmPedido();
        this.dispose();
        pedidos.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void chkPastelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkPastelStateChanged
        if (chkPastel.isSelected() == true) {
            listaPastel.enable(true);
            listaPastel.clearSelection();
            txtQtdePastel.enable(true);
            txtQtdePastel.setText("");
        } else {
            listaPastel.enable(false);
            listaPastel.clearSelection();
            txtQtdePastel.enable(false);
            txtQtdePastel.setText("");
        }
    }//GEN-LAST:event_chkPastelStateChanged

    private void chkPastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPastelActionPerformed
        if (chkPastel.isSelected() == true) {
            listaPastel.enable(true);
            listaPastel.clearSelection();
            txtQtdePastel.enable(true);
            txtQtdePastel.setText("");
        } else {
            listaPastel.enable(false);
            listaPastel.clearSelection();
            txtQtdePastel.enable(false);
            txtQtdePastel.setText("");
        }
    }//GEN-LAST:event_chkPastelActionPerformed

    private void chkPastelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_chkPastelPropertyChange
        if (chkPastel.isSelected() == true) {
            listaPastel.enable(true);
            listaPastel.clearSelection();
            txtQtdePastel.enable(true);
            txtQtdePastel.setText("");
        } else {
            listaPastel.enable(false);
            listaPastel.clearSelection();
            txtQtdePastel.enable(false);
            txtQtdePastel.setText("");
        }
    }//GEN-LAST:event_chkPastelPropertyChange

    private void chkBebidaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkBebidaStateChanged
        if (chkBebida.isSelected() == true) {
            listaBebida.enable(true);
            listaBebida.clearSelection();
            txtQtdeBebida.enable(true);
            txtQtdeBebida.setText("");
        } else {
            listaBebida.enable(false);
            listaBebida.clearSelection();
            txtQtdeBebida.enable(false);
            txtQtdeBebida.setText("");
        }
    }//GEN-LAST:event_chkBebidaStateChanged

    private void chkBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBebidaActionPerformed
        if (chkBebida.isSelected() == true) {
            listaBebida.enable(true);
            listaBebida.clearSelection();
            txtQtdeBebida.enable(true);
            txtQtdeBebida.setText("");
        } else {
            listaBebida.enable(false);
            listaBebida.clearSelection();
            txtQtdeBebida.enable(false);
            txtQtdeBebida.setText("");
        }
    }//GEN-LAST:event_chkBebidaActionPerformed

    private void txtQtdeBebidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdeBebidaKeyTyped
        String caracteres = "987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQtdeBebidaKeyTyped

    private void txtQtdePastelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdePastelKeyTyped
        String caracteres = "987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQtdePastelKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInserirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInserirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInserirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInserirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInserirPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox chkBebida;
    private javax.swing.JCheckBox chkPastel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDataHora;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JList<String> listaBebida;
    private javax.swing.JList<String> listaPastel;
    private javax.swing.JTable tblDados;
    private javax.swing.JTextField txtQtdeBebida;
    private javax.swing.JTextField txtQtdePastel;
    // End of variables declaration//GEN-END:variables
}
